POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Build Login Page",
  "description": "Create React login UI",
  "status": "TODO",
  "priority": "HIGH",
  "deadline": "2026-04-10T18:00:00",
  "boardId": 2
}