### Test 1: Save a new item into the AWS Cloud Database
GET http://localhost:8080/test-save?name=ItemFromHttpFile

###

### Test 2: List all items currently sitting inside AWS
GET http://localhost:8080/test-list